
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/crm_dianzhang_big?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/crm_dianzhang_big?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

lts:
  jobtracker:
    cluster-name: test_cluster
    registry-address: zookeeper://localhost:2181
  jobclient:
    cluster-name: test_cluster
    registry-address: zookeeper://localhost:2181
    node-group: test_jobClient
  tasktracker:
    cluster-name: test_cluster
    registry-address: zookeeper://localhost:2181
    work-threads: 5
    job-runner-class: com.example.lts.test.lts.JobRunnerDispatcher
    node-group: test_trade_TaskTracker